---
- name: Ensure Python is installed on all Linux nodes
  hosts: nodes
  become: yes
  gather_facts: yes

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Only update if the cache is older than 1 hour

    - name: Ensure Python 3 is installed
      apt:
        name: python3
        state: present

    - name: Ensure pip for Python 3 is installed
      apt:
        name: python3-pip
        state: present

    - name: Check Python version
      command: python3 --version
      register: python_version

    - name: Show Python version installed
      debug:
        msg: "Installed Python version is: {{ python_version.stdout }}"


